"use client";
import {use,useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Check,Download,FileText,LoaderCircle,RotateCcw} from "lucide-react";
import {api,errorMessage} from "@/lib/api";
import type {Project} from "@editor/model";
type ExportJob={id:string;status:string;created_at:string;error?:{message?:string}|string;download_url?:string};
const statusLabel:Record<string,string>={queued:"대기 중",running:"만드는 중",validating:"확인 중",succeeded:"출력 완료",failed:"출력 실패",canceled:"취소됨"};
export default function Exports({params}:{params:Promise<{id:string}>}){
const{id}=use(params);const[project,setProject]=useState<Project>();const[jobs,setJobs]=useState<ExportJob[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[retry,setRetry]=useState(0);const[busy,setBusy]=useState<string|null>(null);
useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>|undefined;async function load(){try{const[p,result]=await Promise.all([api<Project>(`/projects/${id}`),api<{items:ExportJob[]}>(`/projects/${id}/exports`)]);if(!active)return;setProject(p);setJobs(result.items);setError("");if(result.items.some(job=>["queued","running","validating"].includes(job.status)))timer=setTimeout(load,2500);}catch(e){if(active)setError(errorMessage(e));}finally{if(active)setLoading(false);}}void load();return()=>{active=false;clearTimeout(timer);};},[id,retry]);
async function retryExport(jobId:string){setBusy(jobId);try{await api(`/jobs/${jobId}/retry`,{method:"POST"});setRetry(n=>n+1);}catch(e){setError(errorMessage(e));}finally{setBusy(null);}}
return <main className="dashboard-content exports-content"><Link className="text-link muted" href={`/app/projects/${id}/editor`}><ArrowLeft size={16}/> 편집기로 돌아가기</Link><div className="page-heading"><div className="eyebrow">READY FOR A CLOSER LOOK</div><h1>검토 파일 이력</h1><p>{project?.name||"프로젝트"} · 앞면과 뒷면, 원래 크기 그대로.</p></div><div className="alert alert-info"><FileText size={18}/><span>이곳의 PDF는 디자인 검토용입니다. 제조사 승인을 받지 않은 데모 구조이며 제작에 사용할 수 없습니다. 다운로드에는 크레딧이 차감되지 않습니다.</span></div>{error&&<div className="alert alert-error" role="alert">{error}<button className="text-link" onClick={()=>setRetry(n=>n+1)}>다시 불러오기</button></div>}{loading?<div className="loading-state"><LoaderCircle className="spin"/> 파일 이력을 확인하고 있어요.</div>:!jobs.length?<div className="empty-state"><FileText size={30}/><h3>아직 출력한 파일이 없어요.</h3><p>편집기에서 검토용 PDF를 만들어 보세요.</p><Link className="button button-dark" href={`/app/projects/${id}/editor`}>디자인 편집하기</Link></div>:<div className="export-history-list">{jobs.map((job,index)=><article className="export-history-row" key={job.id}><span className="export-history-icon"><FileText size={23}/></span><div><h3>검토용 PDF <span>#{jobs.length-index}</span></h3><p>{new Date(job.created_at).toLocaleString("ko-KR")} · {statusLabel[job.status]||job.status}</p>{job.error&&<p className="export-history-error">{typeof job.error==="string"?job.error:job.error.message||"출력 중 문제가 발생했습니다."}</p>}</div>{job.status==="succeeded"?<a className="button button-light button-sm" href={`/api/v1/exports/${job.id}/download`} target="_blank" rel="noreferrer"><Download size={16}/> 다운로드</a>:job.status==="failed"?<button className="button button-light button-sm" onClick={()=>void retryExport(job.id)} disabled={busy===job.id}>{busy===job.id?<LoaderCircle className="spin" size={15}/>:<RotateCcw size={15}/>} 다시 출력</button>:<span className="export-history-pending"><LoaderCircle className="spin" size={17}/> 작업 중</span>}</article>)}</div>}</main>;
}
