"""Generate scene JSON Schema and TypeScript from the actual Pydantic model.

Run from the repo root: python packages/contracts/generate.py [--check]
"""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from services.api.schemas import Scene  # noqa: E402
from services.api.geometry.definitions import DEFINITION_ADAPTER  # noqa: E402


def ts_type(node: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return json.dumps(node["const"], ensure_ascii=False)
    if "enum" in node:
        return " | ".join(json.dumps(value, ensure_ascii=False) for value in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts_type(option) for option in node["anyOf"])
    if "oneOf" in node:
        return " | ".join(ts_type(option) for option in node["oneOf"])
    kind = node.get("type")
    if kind == "array":
        if "prefixItems" in node:
            return "[" + ", ".join(ts_type(item) for item in node["prefixItems"]) + "]"
        return f"Array<{ts_type(node['items'])}>"
    if kind == "object":
        required = node.get("required", [])
        properties = [f"  {key}{'' if key in required else '?'}: {ts_type(value)};" for key, value in node.get("properties", {}).items()]
        return "{\n" + "\n".join(properties) + "\n}"
    return {"string":"string", "number":"number", "integer":"number", "boolean":"boolean", "null":"null"}.get(kind, "unknown")


def outputs() -> dict[str, str]:
    schema = Scene.model_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = "https://phoenix-packaging.invalid/contracts/scene-1.0.schema.json"
    definitions = schema.get("$defs", {})
    typescript = "// Generated by packages/contracts/generate.py. Do not edit manually.\n"
    typescript += "// Runtime geometry and output preflight are additional to these structural types.\n\n"
    for name, definition in definitions.items():
        typescript += f"export type {name} = {ts_type(definition)};\n\n"
    typescript += f"export type Scene = {ts_type(schema)};\n"
    structure=DEFINITION_ADAPTER.json_schema()
    structure["$schema"]="https://json-schema.org/draft/2020-12/schema"
    structure["$id"]="https://phoenix-packaging.invalid/contracts/structure-definition-2.0.schema.json"
    structure_ts="// Generated by packages/contracts/generate.py. Never an approval or executable recipe.\n\n"
    for name,definition in structure.get("$defs",{}).items():
        structure_ts+=f"export type {name} = {ts_type(definition)};\n\n"
    structure_ts+=f"export type StructureDefinitionV2 = {ts_type(structure)};\n"
    return {"scene.schema.json": json.dumps(schema, ensure_ascii=False, indent=2) + "\n", "scene.generated.ts": typescript,
            "structure-definition.schema.json":json.dumps(structure,ensure_ascii=False,indent=2)+"\n","structure-definition.generated.ts":structure_ts}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for filename, content in outputs().items():
        target = Path(__file__).parent / filename
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale contract: {filename}. Run python packages/contracts/generate.py")
        else:
            target.write_text(content, encoding="utf-8")
    print("Scene contracts are current." if args.check else "Scene contracts generated.")
