// Generated by packages/contracts/generate.py. Do not edit manually.
// Runtime geometry and output preflight are additional to these structural types.

export type Face = {
  id: "front" | "back" | "bottom" | "left" | "right" | "top";
  name: string;
  width_mm: number;
  height_mm: number;
  background?: string;
  objects?: Array<SceneObject>;
};

export type Hole = {
  id: string;
  face_id: "front" | "back" | "bottom" | "left" | "right" | "top";
  center_x_mm: number;
  center_y_mm: number;
  diameter_mm: number;
};

export type ImageCrop = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type PouchFeatures = {
  header_height_mm?: number;
  zipper_enabled?: boolean;
  zipper_y_mm?: number;
  zipper_band_mm?: number;
  tear_enabled?: boolean;
  tear_y_mm?: number;
  notch_depth_mm?: number;
  notch_height_mm?: number;
  notch_shape?: "round" | "v";
};

export type SceneObject = {
  id: string;
  type: "text" | "image" | "shape" | "barcode";
  face_id: "front" | "back" | "bottom" | "left" | "right" | "top";
  x_mm: number;
  y_mm: number;
  width_mm: number;
  height_mm: number;
  rotation_deg?: number;
  z_index?: number;
  text?: string | null;
  font_size_pt?: number | null;
  font_id?: "NotoSansKR" | null;
  font_weight?: 400 | 700;
  color?: string | null;
  align?: "left" | "center" | "right" | null;
  asset_id?: string | null;
  crop?: ImageCrop | null;
  visible?: boolean;
  print_enabled?: boolean;
  locked?: boolean;
  opacity?: number;
  line_height?: number | null;
  letter_spacing?: number | null;
  binding_key?: string | null;
  fill?: string | null;
  stroke?: string | null;
  stroke_width_mm?: number | null;
  shape?: "rect" | "ellipse" | "circle" | null;
  barcode_value?: string | null;
  module_mm?: number | null;
  bar_height_mm?: number | null;
  barcode_owned?: boolean;
  barcode_usage?: "retail" | "sample";
};

export type Scene = {
  schema_version?: "1.0";
  template_version_id?: string | null;
  template_kind?: "three-side-seal" | "stand-up-pouch" | "folding-box" | null;
  bottom_mm?: number | null;
  depth_mm?: number | null;
  holes?: Array<Hole>;
  pouch_features?: PouchFeatures | null;
  confirmed_fields?: Array<string>;
  reviewed_face_ids?: Array<"front" | "back" | "bottom" | "left" | "right" | "top">;
  brand_id?: string | null;
  product_variant_id?: string | null;
  workspace_id?: string | null;
  geometry_hash?: string | null;
  active_face_id?: "front" | "back" | "bottom" | "left" | "right" | "top";
  faces: Array<Face>;
};
