// Generated by packages/contracts/generate.py. Do not edit manually.
// Runtime geometry and output preflight are additional to these structural types.

export type Face = {
  id: "front" | "back";
  name: string;
  width_mm: number;
  height_mm: number;
  background?: string;
  objects?: Array<SceneObject>;
};

export type SceneObject = {
  id: string;
  type: "text" | "image" | "shape";
  face_id: "front" | "back";
  x_mm: number;
  y_mm: number;
  width_mm: number;
  height_mm: number;
  rotation_deg?: number;
  z_index?: number;
  text?: string | null;
  font_size_pt?: number | null;
  font_id?: "NotoSansKR" | null;
  color?: string | null;
  align?: "left" | "center" | "right" | null;
  asset_id?: string | null;
  visible?: boolean;
  print_enabled?: boolean;
  locked?: boolean;
  opacity?: number;
  line_height?: number | null;
  letter_spacing?: number | null;
  binding_key?: string | null;
  fill?: string | null;
  stroke?: string | null;
  stroke_width_mm?: number | null;
  shape?: "rect" | "ellipse" | "circle" | null;
};

export type Scene = {
  schema_version?: "1.0";
  template_version_id?: "three-side-seal-demo-v1" | null;
  geometry_hash?: string | null;
  active_face_id?: "front" | "back";
  faces: Array<Face>;
};
