// Generated by packages/contracts/generate.py. Never an approval or executable recipe.

export type Assembly = {
  position_mm: [number, number, number];
  rotation_deg: [-180 | -90 | 0 | 90 | 180, -180 | -90 | 0 | 90 | 180, -180 | -90 | 0 | 90 | 180];
  uv_rotation_deg?: 0 | 90 | 180 | 270;
  mirror_u?: boolean;
  mirror_v?: boolean;
};

export type Dimensions = {
  width_mm: number;
  height_mm: number;
  bottom_mm?: number | null;
  depth_mm?: number | null;
};

export type FixedDefinition = {
  schema_version?: "2.0";
  family: "three-side-seal" | "stand-up-pouch" | "folding-box";
  dimension_semantics: Semantics;
  feature_policy?: "none";
  review_bleed_mm?: 3;
  recipe_id: "fixed-panel-net-v1";
  dimensions: Dimensions;
  panels: Array<Panel>;
  structural_parts?: Array<Part>;
  fold_lines?: Array<Line>;
};

export type Line = {
  x1_mm: number;
  y1_mm: number;
  x2_mm: number;
  y2_mm: number;
};

export type Margins = {
  left?: number;
  right?: number;
  top?: number;
  bottom?: number;
};

export type NetPlacement = {
  x_mm: number;
  y_mm: number;
  rotation_deg?: 0 | 180;
};

export type Panel = {
  id: "front" | "back" | "left" | "right" | "top" | "bottom";
  width_mm: number;
  height_mm: number;
  net: NetPlacement;
  assembly: Assembly;
  safe_inset_mm?: Margins;
  no_print?: Array<Rect>;
  fold?: Array<Line>;
};

export type Part = {
  x_mm: number;
  y_mm: number;
  width_mm: number;
  height_mm: number;
  id: string;
  kind: "glue_tab" | "flap";
  attached_face_id: "front" | "back" | "left" | "right" | "top" | "bottom";
};

export type Range = {
  minimum: number;
  maximum: number;
};

export type Rect = {
  x_mm: number;
  y_mm: number;
  width_mm: number;
  height_mm: number;
};

export type Semantics = {
  basis: "finished_outer" | "panel" | "inner" | "outer";
  bottom_definition?: "expanded_gusset" | null;
  material_thickness_mm?: number | null;
  glue_allowance_mm?: number | null;
  compensation?: "none" | "included_in_fixed_panels";
};

export type SeparatedDefinition = {
  schema_version?: "2.0";
  family?: "three-side-seal";
  dimension_semantics: Semantics;
  feature_policy?: "none";
  review_bleed_mm?: 3;
  recipe_id: "three-side-seal-separated-v1";
  width_range_mm: Range;
  height_range_mm: Range;
  seals_mm: Margins;
  safe_margin_mm?: number;
  panel_gap_mm?: number;
  preview_depth_mm?: number;
};

export type StructureDefinitionV2 = FixedDefinition | SeparatedDefinition;
