"""Transactional credits, subscriptions and immutable payment history."""
from alembic import op
import sqlalchemy as sa

revision = "0004_billing"
down_revision = "0003_job_leases"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_accounts',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('customer_key_encrypted', sa.Text(), nullable=False),
    sa.Column('customer_key_hash', sa.String(length=64), nullable=False),
    sa.Column('billing_key_encrypted', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('customer_key_hash')
    )
    op.create_table('billing_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_billing_outbox_tenant_id'), 'billing_outbox', ['tenant_id'], unique=False)
    op.create_table('credit_wallets',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('ever_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=30), nullable=False),
    sa.Column('next_plan_id', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('billing_anchor', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('billing_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_id', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'period_start', name='uq_subscription_invoice_period')
    )
    op.create_index(op.f('ix_billing_invoices_subscription_id'), 'billing_invoices', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_tenant_id'), 'billing_invoices', ['tenant_id'], unique=False)
    op.create_table('credit_buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('grant_key', sa.String(length=200), nullable=False),
    sa.Column('granted', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Integer(), nullable=False),
    sa.Column('expired', sa.Integer(), nullable=False),
    sa.Column('source_bucket_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('granted = available + reserved + consumed + expired', name='ck_credit_bucket_conservation'),
    sa.CheckConstraint('granted >= 0 AND available >= 0 AND reserved >= 0 AND consumed >= 0 AND expired >= 0', name='ck_credit_bucket_nonnegative'),
    sa.ForeignKeyConstraint(['source_bucket_id'], ['credit_buckets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['credit_wallets.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'grant_key', name='uq_credit_grant')
    )
    op.create_index(op.f('ix_credit_buckets_expires_at'), 'credit_buckets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_credit_buckets_tenant_id'), 'credit_buckets', ['tenant_id'], unique=False)
    op.create_table('credit_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('credit_total', sa.Integer(), nullable=False),
    sa.Column('pricing_version', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('base_revision', sa.Integer(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['credit_wallets.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_quotes_tenant_id'), 'credit_quotes', ['tenant_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('bucket_id', sa.String(length=36), nullable=True),
    sa.Column('event_key', sa.String(length=240), nullable=False),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('operation_key', sa.String(length=200), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("event IN ('GRANT','RESERVE','CAPTURE','RELEASE','EXPIRE','COMPENSATE','ADJUSTMENT')", name='ck_credit_ledger_event'),
    sa.ForeignKeyConstraint(['bucket_id'], ['credit_buckets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['credit_wallets.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_key', name='uq_credit_ledger_event')
    )
    op.create_index(op.f('ix_credit_ledger_tenant_id'), 'credit_ledger', ['tenant_id'], unique=False)
    op.create_table('credit_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('operation_key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('unit_status', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('units > 0 AND unit_cost >= 0 AND total = units * unit_cost', name='ck_credit_reservation_cost'),
    sa.ForeignKeyConstraint(['quote_id'], ['credit_quotes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['credit_wallets.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id'),
    sa.UniqueConstraint('tenant_id', 'operation_key', name='uq_credit_reservation_operation')
    )
    op.create_index(op.f('ix_credit_reservations_expires_at'), 'credit_reservations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_credit_reservations_tenant_id'), 'credit_reservations', ['tenant_id'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('operation_key', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('plan_id', sa.String(length=30), nullable=True),
    sa.Column('source_plan_id', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('pricing_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credits_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0 AND credits >= 0', name='ck_payment_order_nonnegative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('tenant_id', 'operation_key', name='uq_payment_order_operation')
    )
    op.create_index(op.f('ix_payment_orders_tenant_id'), 'payment_orders', ['tenant_id'], unique=False)
    op.create_table('billing_webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('verified_status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_billing_webhooks_tenant_id'), 'billing_webhooks', ['tenant_id'], unique=False)
    op.create_table('credit_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('bucket_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_credit_allocation_amount'),
    sa.ForeignKeyConstraint(['bucket_id'], ['credit_buckets.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['credit_wallets.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reservation_id', 'unit_index', 'bucket_id', name='uq_credit_allocation_unit_bucket')
    )
    op.create_index(op.f('ix_credit_allocations_reservation_id'), 'credit_allocations', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_credit_allocations_tenant_id'), 'credit_allocations', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('provider_payment_key', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('provider_payment_key')
    )
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('production_entitlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('identity_policy', sa.String(length=80), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['credit_reservations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fingerprint', name='uq_production_entitlement')
    )
    op.create_index(op.f('ix_production_entitlements_tenant_id'), 'production_entitlements', ['tenant_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index(op.f('ix_payment_events_tenant_id'), 'payment_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    _protect_history()


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_tenant_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_production_entitlements_tenant_id'), table_name='production_entitlements')
    op.drop_table('production_entitlements')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_credit_allocations_tenant_id'), table_name='credit_allocations')
    op.drop_index(op.f('ix_credit_allocations_reservation_id'), table_name='credit_allocations')
    op.drop_table('credit_allocations')
    op.drop_index(op.f('ix_billing_webhooks_tenant_id'), table_name='billing_webhooks')
    op.drop_table('billing_webhooks')
    op.drop_index(op.f('ix_payment_orders_tenant_id'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_credit_reservations_tenant_id'), table_name='credit_reservations')
    op.drop_index(op.f('ix_credit_reservations_expires_at'), table_name='credit_reservations')
    op.drop_table('credit_reservations')
    op.drop_index(op.f('ix_credit_ledger_tenant_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_credit_quotes_tenant_id'), table_name='credit_quotes')
    op.drop_table('credit_quotes')
    op.drop_index(op.f('ix_credit_buckets_tenant_id'), table_name='credit_buckets')
    op.drop_index(op.f('ix_credit_buckets_expires_at'), table_name='credit_buckets')
    op.drop_table('credit_buckets')
    op.drop_index(op.f('ix_billing_invoices_tenant_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_subscription_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_table('subscriptions')
    op.drop_table('credit_wallets')
    op.drop_index(op.f('ix_billing_outbox_tenant_id'), table_name='billing_outbox')
    op.drop_table('billing_outbox')
    op.drop_table('billing_accounts')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS phoenix_financial_immutable()")


def _protect_history():
    tables = ['billing_accounts', 'billing_invoices', 'billing_outbox', 'billing_webhooks', 'credit_allocations', 'credit_buckets', 'credit_ledger', 'credit_quotes', 'credit_reservations', 'credit_wallets', 'payment_events', 'payment_orders', 'payments', 'production_entitlements', 'subscriptions']
    if op.get_bind().dialect.name == "postgresql":
        for table in tables:
            op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            op.execute(f'REVOKE ALL ON TABLE "{table}" FROM PUBLIC')
            op.execute(f"DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON TABLE \"{table}\" FROM anon; END IF; IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON TABLE \"{table}\" FROM authenticated; END IF; END $$;")
        op.execute("CREATE OR REPLACE FUNCTION phoenix_financial_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Financial history is append-only'; END; $$")
        for table in ("credit_ledger", "payments", "payment_events"):
            op.execute(f'CREATE TRIGGER "{table}_immutable" BEFORE UPDATE OR DELETE ON "{table}" FOR EACH ROW EXECUTE FUNCTION phoenix_financial_immutable()')
    else:
        for table in ("credit_ledger", "payments", "payment_events"):
            for operation in ("UPDATE", "DELETE"):
                op.execute(f"CREATE TRIGGER {table}_no_{operation.lower()} BEFORE {operation} ON {table} BEGIN SELECT RAISE(ABORT, 'Financial history is append-only'); END")
