"""platform_features

Revision ID: 0005_platform_features
Revises: 0004_billing
"""
from alembic import op
import sqlalchemy as sa


revision = '0005_platform_features'
down_revision = '0004_billing'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_budgets',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('requested_units', sa.Integer(), nullable=False),
    sa.CheckConstraint('requested_units >= 0', name='ck_provider_budget_nonnegative'),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_tenant_id'), 'workspaces', ['tenant_id'], unique=False)
    op.create_table('approval_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_approval_evidence_tenant_id'), 'approval_evidence', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('font_ids', sa.JSON(), nullable=False),
    sa.Column('logo_asset_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['logo_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_tenant_id'), 'brands', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_membership')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('registry_versions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('manufacturer', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('approval', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_versions_kind'), 'registry_versions', ['kind'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('workspace_ids', sa.JSON(), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_team_invitations_email'), 'team_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_team_invitations_tenant_id'), 'team_invitations', ['tenant_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_index(op.f('ix_workspace_members_tenant_id'), 'workspace_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('preflight_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('conditions_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['project_revisions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preflight_runs_project_id'), 'preflight_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_preflight_runs_tenant_id'), 'preflight_runs', ['tenant_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_variants_tenant_id'), 'variants', ['tenant_id'], unique=False)
    op.create_table('ai_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('provider_request_id', sa.String(length=160), nullable=True),
    sa.Column('result_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'unit_index', name='uq_ai_unit')
    )
    op.create_index(op.f('ix_ai_units_job_id'), 'ai_units', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_units_status'), 'ai_units', ['status'], unique=False)
    op.create_index(op.f('ix_ai_units_tenant_id'), 'ai_units', ['tenant_id'], unique=False)
    op.create_table('printer_intake_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('manufacturer', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['approval_evidence.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_intake_records_tenant_id'), 'printer_intake_records', ['tenant_id'], unique=False)
    op.create_table('provider_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('request_id', sa.String(length=160), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('cost_is_estimate', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['ai_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_attempts_tenant_id'), 'provider_attempts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_provider_attempts_unit_id'), 'provider_attempts', ['unit_id'], unique=False)
    op.add_column('assets', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('assets', sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False))
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False)
    with op.batch_alter_table('login_sessions') as batch:
        batch.add_column(sa.Column('active_tenant_id', sa.String(length=36), nullable=True))
        batch.create_foreign_key('fk_session_active_tenant', 'tenants', ['active_tenant_id'], ['id'])
    op.add_column('projects', sa.Column('bottom_mm', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('depth_mm', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('brand_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('product_variant_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('template_version_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('print_profile_version_id', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('material', sa.String(length=120), server_default='', nullable=False))
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.drop_index('uq_running_export_tenant',table_name='jobs')
    op.create_index('uq_running_export_tenant','jobs',['tenant_id'],unique=True,postgresql_where=sa.text("status = 'running' AND kind IN ('review_export','production_export')"),sqlite_where=sa.text("status = 'running' AND kind IN ('review_export','production_export')"))
    if op.get_bind().dialect.name=='postgresql':
        tables=('provider_budgets','workspaces','approval_evidence','audit_events','brands','memberships','registry_versions','team_invitations','workspace_members','products','preflight_runs','variants','ai_units','printer_intake_records','provider_attempts')
        for table in tables:
            op.execute(sa.text(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'))
            op.execute(sa.text(f'REVOKE ALL ON TABLE "{table}" FROM PUBLIC'))
            for role in ('anon','authenticated'):
                if op.get_bind().scalar(sa.text('SELECT 1 FROM pg_roles WHERE rolname=:role'),{'role':role}):
                    op.execute(sa.text(f'REVOKE ALL ON TABLE "{table}" FROM "{role}"'))
    # ### end Alembic commands ###


def downgrade():
    op.drop_index('uq_running_export_tenant',table_name='jobs')
    op.create_index('uq_running_export_tenant','jobs',['tenant_id'],unique=True,postgresql_where=sa.text("status = 'running'"),sqlite_where=sa.text("status = 'running'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_column('projects', 'material')
    op.drop_column('projects', 'print_profile_version_id')
    op.drop_column('projects', 'template_version_id')
    op.drop_column('projects', 'workspace_id')
    op.drop_column('projects', 'product_variant_id')
    op.drop_column('projects', 'brand_id')
    op.drop_column('projects', 'depth_mm')
    op.drop_column('projects', 'bottom_mm')
    with op.batch_alter_table('login_sessions') as batch:
        batch.drop_constraint('fk_session_active_tenant',type_='foreignkey')
        batch.drop_column('active_tenant_id')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets')
    op.drop_column('assets', 'metadata_json')
    op.drop_column('assets', 'workspace_id')
    op.drop_index(op.f('ix_provider_attempts_unit_id'), table_name='provider_attempts')
    op.drop_index(op.f('ix_provider_attempts_tenant_id'), table_name='provider_attempts')
    op.drop_table('provider_attempts')
    op.drop_index(op.f('ix_printer_intake_records_tenant_id'), table_name='printer_intake_records')
    op.drop_table('printer_intake_records')
    op.drop_index(op.f('ix_ai_units_tenant_id'), table_name='ai_units')
    op.drop_index(op.f('ix_ai_units_status'), table_name='ai_units')
    op.drop_index(op.f('ix_ai_units_job_id'), table_name='ai_units')
    op.drop_table('ai_units')
    op.drop_index(op.f('ix_variants_tenant_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_preflight_runs_tenant_id'), table_name='preflight_runs')
    op.drop_index(op.f('ix_preflight_runs_project_id'), table_name='preflight_runs')
    op.drop_table('preflight_runs')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_tenant_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_team_invitations_tenant_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_email'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_registry_versions_kind'), table_name='registry_versions')
    op.drop_table('registry_versions')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_brands_tenant_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_approval_evidence_tenant_id'), table_name='approval_evidence')
    op.drop_table('approval_evidence')
    op.drop_index(op.f('ix_workspaces_tenant_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_table('provider_budgets')
    # ### end Alembic commands ###
