"""direct_uploads

Revision ID: 0006_direct_uploads
Revises: 0005_platform_features
"""
from alembic import op
import sqlalchemy as sa


revision = '0006_direct_uploads'
down_revision = '0005_platform_features'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_upload_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_asset_upload_sessions_tenant_id'), 'asset_upload_sessions', ['tenant_id'], unique=False)
    if op.get_bind().dialect.name=='postgresql':
        op.execute(sa.text('ALTER TABLE asset_upload_sessions ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text('REVOKE ALL ON TABLE asset_upload_sessions FROM PUBLIC'))
        for role in ('anon','authenticated'):
            if op.get_bind().scalar(sa.text('SELECT 1 FROM pg_roles WHERE rolname=:role'),{'role':role}):
                op.execute(sa.text(f'REVOKE ALL ON TABLE asset_upload_sessions FROM "{role}"'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_upload_sessions_tenant_id'), table_name='asset_upload_sessions')
    op.drop_table('asset_upload_sessions')
    # ### end Alembic commands ###
